version: '3.8'
services:
  db:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redisserver
    ports:
      - "6380:6379"
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    container_name: rediscommander
    environment:
      - REDIS_HOSTS=local:redis:6379
volumes:
  pgdata: